// <auto-generated />
using AllTrialsAndWalks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AllTrialsAndWalks.Migrations.AllTrialsAuthDbcontextMigrations
{
    [DbContext(typeof(AllTrialsAuthDbcontext))]
    [Migration("20240308051501_Creating auth database")]
    partial class Creatingauthdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "95e5ac78-a51a-4555-b841-e8389117f74c",
                            ConcurrencyStamp = "95e5ac78-a51a-4555-b841-e8389117f74c",
                            Name = "Reader",
                            NormalizedName = "READER"
                        },
                        new
                        {
                            Id = "65286adb-78f2-4787-bf71-e9f0eef7faf6",
                            ConcurrencyStamp = "65286adb-78f2-4787-bf71-e9f0eef7faf6",
                            Name = "Writer",
                            NormalizedName = "WRITER"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
